package interactionPlugins.fileSubmission

import org.scalajs.dom.File

object TurtleFileSubmission {


  def readBytes(file: File): Array[Byte] = ???
  
  def renderFile(fileBytes: Array[Byte]): String = {
    // input: a file to a turtlestitch xml file (version 2)
    // desired: the data of the image that gets generated by the code in the turtlestitch xml file
    val imageDataPngBase64 = ???
    "data:image/png;base64, " + imageDataPngBase64
  }

}
