import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {chromium} from 'playwright';

const root = path.resolve(import.meta.dirname, '../..');
const origin = 'http://localhost:9000';
const mime = {'.html':'text/html', '.js':'text/javascript', '.mjs':'text/javascript', '.css':'text/css', '.json':'application/json', '.svg':'image/svg+xml', '.png':'image/png'};

test('evacuation workbook plays EVA2 locally, records/restores comparisons and saves after reload', async () => {
  await fs.access(path.join(root, 'artifacts/newest/client.js'));
  const browser = await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium', args:['--no-sandbox']});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:900}});
    page.setDefaultTimeout(60000);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.route('**/*', async route => {
      const url = new URL(route.request().url());
      if (url.origin !== origin) return route.abort();
      const file = path.resolve(root, '.' + decodeURIComponent(url.pathname));
      if (!file.startsWith(root + path.sep)) return route.abort();
      try { await route.fulfill({body:await fs.readFile(file), contentType:mime[path.extname(file)] || 'application/octet-stream'}); }
      catch { await route.fulfill({status:404,body:'Not found'}); }
    });
    await page.goto(origin + '/homepage/evacuationWorkbook/index.html');
    const login = page.locator('.section-register .login-area').nth(1).locator('button');
    await login.click();
    const chapter = page.locator('.section-block').filter({hasText:'Evacuation experiment'});
    await chapter.click();
    const preview = page.locator('.evacuation-simulation-preview');
    await preview.waitFor();
    assert.match(await preview.innerText(), /4 people · 1 exits · 0 recorded runs/);
    const open = page.getByRole('button', {name:/Open editor/i});
    await open.click();
    const editor = page.locator('dialog[open] .evacuation-experiment');
    await editor.waitFor();
    const action = name => editor.getByRole('button', {name,exact:true});
    const speed = editor.getByRole('textbox',{name:'Assumed speed (m/s, 0.01–20)'});
    await speed.fill('-');
    assert(await action('Prepare simulation').isDisabled());
    assert.match(await editor.getByRole('alert').innerText(), /finite speed/);
    await speed.fill('1,0');
    await action('Prepare simulation').click();
    const status = editor.locator('.evacuation-playback [role=status]');
    await status.waitFor();
    assert.match(await status.innerText(), /Step 0/);
    await action('Next step').click();
    assert.match(await status.innerText(), /Step 1/);
    await action('Previous step').click();
    assert.match(await status.innerText(), /Step 0/);
    await action('Play').click();
    await action('Pause').click();
    await action('Restart playback').click();
    await action('Play').click();
    await page.waitForFunction(() => document.querySelector('.evacuation-playback [role=status]')?.textContent.includes('Evacuated in 6'));
    assert.equal(await editor.locator('.evacuation-playback .evacuation-cell--person').count(),0);
    const label = editor.getByRole('textbox',{name:'Run label'});
    await label.fill('Baseline');
    await action('Record run').click();
    const rows = editor.locator('.evacuation-measurements tbody tr');
    assert.equal(await rows.count(),1);
    assert.match(await rows.first().innerText(), /Baseline/);
    assert.equal(await rows.first().locator('td').nth(2).innerText(),'6');
    assert.equal(await rows.first().locator('td').nth(3).innerText(),'3.00');
    await speed.fill('2');
    await action('Prepare simulation').click();
    await action('Play').click();
    await page.waitForFunction(() => document.querySelector('.evacuation-playback [role=status]')?.textContent.includes('Evacuated in 6'));
    await label.fill('Faster assumption');
    await action('Record run').click();
    assert.equal(await rows.count(),2);
    assert.equal(await rows.nth(1).locator('td').nth(3).innerText(),'1.50');
    assert.equal(await rows.first().locator('td').nth(3).innerText(),'3.00','earlier measurements keep their original speed');
    await rows.first().getByRole('button',{name:'Restore scenario'}).click();
    assert.equal(Number(await speed.inputValue()),1);
    await action('Exit').click();
    await editor.locator('.evacuation-cell').nth(7).click();
    await action('Prepare simulation').click();
    await action('Play').click();
    await page.waitForFunction(() => document.querySelector('.evacuation-playback [role=status]')?.textContent.includes('Evacuated'));
    await label.fill('Two exits');
    await action('Record run').click();
    assert.equal(await rows.count(),3);
    assert.match(await rows.nth(2).locator('td').nth(1).innerText(), /2 exits/);
    assert.match(await rows.first().locator('td').nth(1).innerText(), /1 exits/);
    await page.setViewportSize({width:390,height:844});
    const layout = await editor.evaluate(el => {
      const rect = el.getBoundingClientRect();
      return {left:rect.left,right:rect.right,width:innerWidth,inline:el.querySelectorAll('[style],style').length};
    });
    assert(layout.left >= 0 && layout.right <= layout.width + 1, JSON.stringify(layout));
    assert.equal(layout.inline,0);
    await page.locator('.fullscreen-close-button').click();
    assert.match(await preview.innerText(), /3 recorded runs/);
    await page.waitForFunction(async () => {
      const db = await new Promise((resolve,reject) => {const r=indexedDB.open('EvaDidInteractionDB');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
      const rows = await new Promise((resolve,reject) => {const r=db.transaction('variableHistoryStore').objectStore('variableHistoryStore').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
      db.close(); return rows.some(row => JSON.stringify(row).includes('Two exits'));
    });
    await page.reload();
    if (await login.isVisible()) await login.click();
    await chapter.click();
    await preview.waitFor();
    assert.match(await preview.innerText(), /3 recorded runs/);
    await open.click();
    assert.equal(await rows.count(),3);
    await rows.nth(2).getByRole('button',{name:'Remove run'}).click();
    assert.equal(await rows.count(),2);
    await rows.first().getByRole('button',{name:'Restore scenario'}).click();
    await action('Prepare simulation').click();
    await action('Play').click();
    await page.locator('.fullscreen-close-button').click();
    await open.click();
    assert.equal(await editor.locator('.evacuation-playback').count(),0,'closing disposes transient playback');
    assert.equal(await rows.count(),2,'recorded snapshots survive reopening');
    assert.deepEqual(errors,[]);
  } finally { await browser.close(); }
});
