#!/usr/bin/env python3
"""Import original teaching examples without executing Python or adding dependencies."""
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'resources/workbookresources/phishing/Arbeitsheft_Phishing/E-Mail-Simulation/skripts/mails.py'
TARGET = ROOT / 'modules/client/src/main/scala/it/evadid/homepage/workbook/content/PhishingMailboxData.scala'
mails = []
for node in ast.walk(ast.parse(SOURCE.read_text(encoding='utf-8'))):
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'Email':
        fields = {arg.arg: ast.literal_eval(arg.value) for arg in node.keywords}
        mails.append(dict(id=f'phishing-{len(mails)+1:02d}', sender=fields['sender'],
                          senderName=fields['sender_name'], subject=fields['subject'], body=fields['body'],
                          realFolder='Posteingang', expectedFolder=fields['real_folder'],
                          attachment=fields['attachment'], timestamp=fields['timestamp'],
                          bodyHtml=True, recipients=['opa.jürgen@gmail.com']))
assert len(mails) == 15
payload = json.dumps(mails, ensure_ascii=False, indent=2)
assert '"""' not in payload
TARGET.write_text('''package it.evadid.homepage.workbook.content

import it.evadid.workbook.elements.interactionElements.emailSimulator.{Mail, InboxState}

/** Generated by tools/dev/import-phishing-mails.py from the original workbook assets. */
object PhishingMailboxData {
  lazy val initialInbox: InboxState = InboxState.withMails(upickle.default.read[List[Mail]](data))
  private val data = """''' + payload + '''"""
}
''', encoding='utf-8')
print(f'Imported {len(mails)} examples into {TARGET.relative_to(ROOT)}')
