package it.evadid.evacuation.eva2.algorithm.escaping

import it.evadid.core.datastructures.matrix.*
import it.evadid.evacuation.core.algorithm.routing.RoutingOptionsToDestinationCalculator
import it.evadid.evacuation.core.graphic.spritemap.EvaSpriteMap
import it.evadid.evacuation.eva2.graphic.EvaMapDrawer
import it.evadid.evacuation.eva2.io.{FloorMapIO, ScenarioCache}
import it.evadid.evacuation.eva2.model.*

import java.awt.Color
import java.io.File
import java.nio.file.Path
import java.util.Date
import scala.concurrent.ExecutionContextExecutor

case class Evacuation(initialState: EvaFloorMap, states: List[EvaFloorMap], steps: List[Int]) {

  def stepNr(stateNr: Int): Int =
    steps.count(_ <= stateNr)

  def nextMicroStep(curStep: Int): Int = {
    if (curStep >= states.size - 1) states.size - 1
    else if (curStep < 0) 0
    else curStep + 1
  }

  def previousMicroStep(curStep: Int): Int = {
    if (curStep >= states.size) states.size - 1
    else if (curStep < 1) 0
    else curStep - 1
  }

  def nextStep(curStep: Int): Int = {
    steps.filter(_ > curStep).minOption.getOrElse(states.size - 1)
  }

  def stepBeginOfState(curState: Int): Int = {
    if (steps.contains(curState)) {
      curState
    } else {
      previousStep(curState)
    }
  }

  def previousStep(curStep: Int): Int = {
    steps.filter(_ < curStep).maxOption.getOrElse(0)
  }

  def getStepsAsList(): List[EvaFloorMap] =
    steps.map(states(_))

  def tracePerson(id: Integer): List[PositionInMatrix] = getStepsAsList().flatMap(_.getPositionOfPerson(id))

  def getNextDirectionOfPerson(currentState: Integer, id: Integer): Option[Direction] = {

    val curPos = states(currentState).getPositionOfPerson(id)

    var nextState = nextStep(currentState)
    var nextPos = states(nextState).getPositionOfPerson(id)

    while (nextPos.nonEmpty && curPos == nextPos && nextState != states.length - 1) {
      nextState = nextStep(nextState)
      nextPos = states(nextState).getPositionOfPerson(id)
    }

    if (curPos.isDefined && nextPos.isDefined) Direction.fromPosition(nextPos.get.cPos.sub(curPos.get))
    else None


  }
}

object Evacuation {

  implicit val context: ExecutionContextExecutor = scala.concurrent.ExecutionContext.global

  val defaultScenario: String = "default:AAAAAAUAAAADAAAADwEAAQEBAhADWAUSICJiICI=:DBIAAgEBcwEDAQEBdA=="
  val miniScenario: String = "default:AAAAAAYAAAAIAAAAMAEAAQECEREQERESEWIQERESEREQERFoEREQERFoEREQERESEREQERESEREgISEiERE=:DhgAAQEBAgEBAQIBAQECAQEBAhgAAgECAgIFAgYYAAJzBHQCcw=="
  val miniScenarioTwo: String = "default:AAAAAAYAAAAIAAAAMAEAAQECEREQERESEWIQERESEREQERFoEREQERFoEREQERESEREQERESEWIgISEiERE=:DhgAAQEBAgEBAQIBAQECAQEBAhgAAgECAgIFAgYYAAJzBHQCcw=="
  val miniScenarioBig: String = "default:AAAAAAYAAAAIAAAAMAEAAQECYGEQEREScHEQERESEREQERFoEREQERFoEREQERESEREQERESYGEgISEicHE=:DhgAAQEBAgEBAQIBAQECAQEBAhgAAgECAgIFAgYYAAJzBHQCcw=="
  val sporthall16: String = "default:AQMAASsDAAEQAgABAgGwAQEBABUBATMGAQECDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURAUQBWAUhAWUGIQEFBhEBEBURATcBEQQUAhEEFAIRATcGEQEQJxEBYAFhAREBECcRAXABcQERARAVEQFGAREEFAIRBBQCEQFGBhEBEBURATQBOAUBAVUGAQElBhEBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBIBUhAUMGIQEiDRE=:DjAABgIDFwIYAxcCGDAAAQUBBwEIAQoBDAEDAQQBAwICAQMBCwEMAg0BDDAABnMKdA=="
  val sporthall40: String = "default:AQMAASsDAAEQAgABAgGwAQEBABUBATMGAQECDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURAUQBWAUhAWUGIQEFBhEBEBURATcBEQQUAhEEFAIRATcGEQEQJxEBYAFhAREBECcRAXABcQERARAVEQFGAREEFAIRBBQCEQFGBhEBEBURATQBOAUBAVUGAQElBhEBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBIBUhAUMGIQEiDRE=:DtIACQIBAwEGAQcBCgELAgMBAgcDCQYJBwkKCQsDFwIYAxcCGNIAAQUBBwEJAQsBBAEGAQgBCgYMAQQCAwEFAQYBBwEIAQkBCgILAQoBCQEIAQcBBgEFAQQCAwEEAQYBBQEHAQgBCQEKAgsBCgEJAQgBBwEGAQUBBAIDAQQBBQEGAQcBCAEJAQoBCwEEAQMCAgEDAQsBDAINAQzSADxzCnQ="


  val sporthall30: String = "default:AQMAASsDAAEQAgABAgGwAQEBABUBATMGAQECDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURAUQBWAUhAWUGIQEFBhEBEBURATcBEQQUAhEEFAIRATcGEQEQJxEBYAFhAREBECcRAXABcQERARAVEQFGAREEFAIRBBQCEQFGBhEBEBURATQBOAUBAVUGAQElBhEBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBIBUhAUMGIQEiDRE=:DngABAMDFwIYAxcCGAESAREGBAISAREBEgERAhIBEQEKAgsBCgMLAgoBC3gAAQwBAwEFAQoBBAEDAgIBAwELAQwCDQEMAwMBBQEHAQgBCgEMAQcBCAIKAgwEBQIDAQcBCAIKAgx4AARzCnQQcwp1"

  val graphExample: String = "default:AQMAASsDAAEQAgABAgGwAQEBABUBATMGAQECDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURAUQBWAUhAWUGIQEFBhEBEBURATcBEQQUAhEEFAIRATcGEQEQJxEBYAFhAREBECcRAXABcQERARAVEQFGAREEFAIRBBQCEQFGBhEBEBURATQBOAUBAVUGAQElBhEBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBIBUhAUMGIQEiDRE=:DngAAQMBCgELAwMDCgULAxcCGAMXAhgBEgERBgQCEgERARIBEQISARF4AAMMAQMBBQIKAQUCAwEFAQcBCAEKAQQBAwICAQMBCwEMAg0BDAMDAQUBBwEIAQoBDAEHAQgCCgIMAgV4AA5zCnQQcw=="
  val extremeExample: String = "default:AQMAAQ4DAAEHAwABYgEBAQAJAQECAxEBEAkRAWgDEQEQBREEIQFkATABMQEyARAJEQFoAUABQQFCARAFEQQBAVQBUAFRAVIBEAkRAWgDEQEgCSEBIgMR:Di0AAwMDBAMCAwEwAAECAQMCBAEDAgIBAwIEAQMCAgEDAQQtAA9z"

  val distributionTest: String = "default:AQMAASsDAAEQAgABAgGwAQEBABUBATMGAQECDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURAUQBWAUhAWUEIQFiASEBBQYRARAVEQE3DhEBYgURARAkEQFiBREBECQRAWIFEQEQFREBRgIRARQLEQFiBREBEBURATQBOAUBAVUGAQElBhEBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBEBURARAGEQESDREBIBUhAUMGIQEiDRE=:DqIAAxcCGAMXAhgCEgERAhIBEQEYARoCGQIaARkBGAMZAxoBEQISBBEBEgIRAhIBEQESChCiAAEEAQMCAgEDAQsBDAINAQwBBwEIAgoCBQMEAgMCAgELAQwBDQILAQwBDQILAgkBCAEHAgYBAwIEAQMDDAELAQoBCQEGAQUBBAEDAQcBCKIACnQGcw50DnUKcw=="

  val informatikMit270: String = "default:AQMAAbQDAAFWAgABPAF4AQFtEQESAQAjAQECARCNEQESARAjEQESARCNEQESARAjEQESARCCEQFgAWEJEQESARAjEQESARCCEQFwAXEJEQESARAjEQESARCBEQEAAhEBAgEABAEBAgEQAREBEgEQIxEBEgEQgREBEAIRARIBEAQRARIBEAERARIBECMRARIBEIERARACEQESARAEEQESARABEQESARAjEQESARAxEQFgAWFOEQEQAhEBEgEQBBEBEgEQAREBEgEQIxEBEgEQMREBcAFxThEBIAIRASIBEAQRARIBIAEhASIBECMRARIBICAhBBEBEgEAAwEBAgEAAgEBAgEAAgECEQEBAQIBAAwBAQIBABQBAQIBABMBAQIBAAsBAQIBAAQBAQIBAAIRAQIBEAERARICEQESAQABAQECARAjEQFnAQEBAgUBAQIYAQECBCEBIgEQAxEBEgEQAhEBEgEQBREBEgEQDBEBEgEQFBEBEgEQExEBEgEQCxEBEgEQBBEBEgEQAhEBEgEQAREBEgIRARIBEAERARIBECURARIFEQESGBEBEgEABAEBNgMRARIBEAIRARIBEAURARIBEAwRARIBEBQRARIBEBMRARIBEAsRARIBEAQRARIBEAIRARIBEAERARICEQESARABEQESARAlEQESBREBEhgRARIBEAgRARIBEAIRARIBEAURARIBEAwRARIBEBQRARIBEBMRARIBEAsRARIBAAQBAQIBEAIRARIBEAERARICEQESARABEQESARAlEQESAhEBEgIRARIYEQESARAIEQESARACEQESARAFEQESARAMEQESARAUEQESARATEQESARALEQESARAIEQESARABEQESAhEBEgEQAREBEgEQJREBEgIRARICEQESGBEBEgEQCBEBEgEQAhEBEgEQBREBEgEQDBEBEgEQFBEBEgEQExEBEgEQCxEBEgEQBBEBEgEQAhEBEgEQAREBEgIRARIBEAERARIBECURARICEQESAhEBEhgRARIBEAgRARIBEAIRARIBEAURARIBEAwRARIBEBQRARIBEBMRARIBEAsRARIBIAQhASIBEAgRARIBEAERARIBECURARICEQESAhEBEhgRARIBEAgRARIBEAIRARIBEAURARIBEAwRARIBEBQRARIBEBMRARIBEAsRARIBEAQRARIBEAgRARIBEAERARIBEBwRARIBAAECARAFEQESAhEBEgIRARIYEQESARAIEQESARACEQESARAFEQESARAMEQESARAUEQESARATEQESARALEQESARAEEQESARAIEQESARABEQESARAcEQESARABEgEQBREBEgURARIYEQESARAIEQESARACEQESARAFEQESARAMEQESARAUEQESARATEQESARALEQESARAOEQESARABEQESARAcEQESARABEgEQBREBEgURARIYEQESARAIEQESARAXEQESARAUEQESARATEQESARALEQESASAEIQEiARAIEQESASABIQEiASAcIQEiARABEgEgBSEBIgEhBBEBIhghASIBIAYhAhEBIgEgAiEBIgEgAiECEQEhASIBIAwhASIBEBQRARIBEBMRARIBEAsRARIBAAQBAQIBEE4RAQAHAQECHhEBEBQRARIBEBMRARIBEAsRARIBEAQRARIBEE0RAQABNwcRARIeEQEQFBEBEgEQExEBEgEQCxEBEgEQBBEBEgEQSxECIQEQCBEBEh4RARAUEQESARATEQESARALEQESARBREQEAAQEBNwgRARIeEQEQFBEBEgEQExEBEgEQCxEBEgEQBBEBEgEQBBEBEgEABAEBAjMBASAHIQFGBBEBEAoRARIeEQEQFBEBEgEQExEBEgEQCxEBEgEQBBEBEgEgBBEBIgEQBBEBEjsRASADIQEAATcKEQESHhEBEBQRARIBEBMRARIBEAsRARIBEAQRARIBAAQRAQIBEAQRARI7EQESAQACAQE2CxEBEh4RASAFIQIRDSEBIgEgECECEQEhASIBIAkhAhEBIgEgBCEBIgEQBBEBEgEQBBEBEjsRARIBEA4RARJhEQESASAEIQEiOxEBEgEQDhEBEmERARIBEAQRARI7EQESARAOEQESIREBEgEUBQcIJwEUARAvEQESARAEEQESOxEBEgEQDhEBEmERARIBIAQhASIuIQFGDBEBEgEQDhEBEmERARI0EQEgBCEBRwcRARIBEA4RARJhEQESOREBIAchASIBEA4RARIhEQESARQFBwgnARQBEC8RARJREQESIREBEj8RARJREQESIREBEj8RARJREQESIREBEj8RARJREQESIREBEj8RARJREQESIREBEjURARIBAAQRAQIBEAIRARJQEQFgAWEhEQESNREBEgEQBBEBEgEQAhEBElARAXABcSERARIxEQFWAyEBIgEgBBEBIgEgAiEBIlERARIhEQESMREBEgMRARIBAAQRAQIBEFQRARIhEQESMREBEgMRARIBEAQRARIBEFQRARIhEQESMREBEgMRARIBIAQRASIBEFQRARIhEQESMREBEgURAWABYQFgAWFWEQESISEBIgkhBhECIQERCyEBEQshAREDIQERAyEBIgURAXABcQFwAXFfEQESFREBEAsRARIGEQEQDBEBEAIRARIMEQEQBBEBEmgRARIVEQEQCxEBEgYRARAMEQEQAhEBEgwRARAEEQESaBEBEhURARASEQEQDBEBEAIRARIMEQEQBBEBEmgRARIVEQEQEhEBEAwRARACEQESDBEBEAQRARJjEQUhASIVEQEQCxEBEgYRARAMEQEgAiEBIgwRARAEEQESYxEBEAQRARIVEQEgCyEBIgYRARANEQESDhEBEAQRARJjEQEQBBEBEiERARIGEQEQDREBEg4RARAEEQESYxEBEAQRARIhEQESBhEBEA0RARIOEQEQBBEBEmMRARAEEQESIREBEgYRARANEQESDhEBEAIRAVYBIQEiYxEBIAFGAxEBEgEhAUYfEQESBhEBIA0hASIOIQEgAiEBIgERARJkEQEQBREBEB8RARIGEQEQIREBEmQRARAFEQEQHxEBEgYRARAhEQESZBEBEAURARAfEQESBhEBECERARJkEQEQBREBEB8RARIGEQEQIREBEmQRASAFIQEQHxEBEgYRARAhEQESahEBEB8RARIGEQEQIREBEmoRARAfEQESBhEBECERARJqEQEQHxEBEgYRARAhEQESahEBEB8RARIGEQEQIREBEmoRASACEQEhGxEBIQEiBhEBIAEhIBEBEmsRAWABYQESGREBVgEhARAIEQESASEBRhoRASEBAAFgAWEBAWsRAXABcQESGREBEgwRARAaEQEQAREBcAFxbhEBEgEhGBEBEgwRARAZEQEhARByEQESGBEBEgwRARAZEQEQcxEBEhgRARIMEQEQGREBEHMRARIBIRYRAVYBIgwRASABRhcRASEBEHQRARIWEQESDhEBEBcRARB1EQESFhEBEg4RARAWEQEhARB1EQESASEVEQESDhEBEBYRARB3EQESOxEBEHcRARI6EQEhARB3EQESASETEQFWASIOEQEgAUYUEQEQeREBEhMRARIQEQEQFBEBEHkRARITEQESBgEDEQcBARATEQEhARB5EQESASESEQESBhEBMAExATIHEQEQExEBEHsRARISEQESBhEBQAFBAUIHEQEQEhEBIQEQexEBEhIRARIGEQFQAVEBUgcRARASEQEQfBEBEhIhASIQEQEgEiEBEGUR:Dv8A/wD/AA8AARwBUgEaAUABMAEYAVYBJQEXAUUBJwEbAT0BJAESAjMBKQFMARMBFwExASMBJQE/AScBGwE7ATwBIwFBAVABGwFQAScBRgFVAUcBSAEpASUBHQEnATsBFgE/ATMBGgFFAVMBMAEZASQBEQEUARABHAFSAT8BOgE8ASkBSgEUASYBHwFKATkBMwEbAUgBVAEmATsBRgFKAUIBFQFKAToBPAFWAU4BVAFDATgBTwEcAR0BKAFGARgBHAMfAVUBGAEUASABRgFCAUcBPgEjATIBVAEeATsBSAFNATwBRgFQAR4BGAFCAUYBJQE/ASYBGQEbARoBIAESATgBRQE/AScBKQExAUwBUAE/ARwBLwEWAT0BSAFSAUMBPgElARoBPAEXARwBKQFRATgBLwFQARsBRgE8AUkBRAFGAVEBJQFCAS8BMQEeAVABTgFJAUcBOwE/AVUBOwEZARsBGgElAS8BOwE/AVYBSQFFAT0BPwEWAT8BEAFHATMBEAFUARkBFgFMATsBQQEoARIBJgFSAT0BEgE/ATMBFwElASkBIAE+AVEBVAFDAUYBUwEUAUkBGAEWAUoBFgE/AUYBHAEvAVUBPQEdAScBMQEaAVIBUQEoAVIBFAE7ASgBSQFIASQBMgEYAScBUwEkARIBKAFTAT0BSgFEARMBQwE7ASUBJgEnAS8BVP8A/wD/AA8AAT8BEwENAT0BFgE2ARUBGAE0AUoBEAE2AUwBPAE3ARQBDgEYAUsBNQENARQBRgEUAUoBSAFBARgBOwFKAT8BPAE0AUkBDAFMARABFwEVARYBPgFBARQBDgI9AQwBNgEOARUBDgFJAT4BNQE3ATUBSwEVARYBOwE9AQwBPwE1ARYBDQEXAT0BGAE/AQ4CPAEQARcBFQFIAT8BQQI/ARcBTQE+AjsBSwELAT0BPgFBAQsBDwE9AT8BQQEVAUcBMwELAkoBPwFKAUgBDgETAQ8BFAE9AUsBSgEVAT4BCwFLAUwBPQEQAQ4BQAE0ATgBRwENAj8BEAE7AUYBDgEYAUkBTQE/AQ0BDgENARQBGQEOAUoBDgEWAUsBDgE2AUcBEAEOAT0BEAFAAT0BDgEWAQwBSAEZARABDgE9ARYBDAE/AUsBSQEOARABPQFIAgwBOAFJAQ8BRgEYAUgBGAETAT8BDAEQAUwBCwEUATMBDAEQATcBDgENAQ8BTQFKATsBQAE9AQ4BPAEYAUEBEAEWATgBSgEUAQ8BFgEMARcBPQE/AT4BQQEXAQ8BQQE9AT8BDAFIAUkBFAEOAQwBDQE+ARABCwFAAT4BPAEXAT0BTAEOARABQQFAARYBSQEYAQwBSAEzARYBEAFIARkBTAI/ARYBDAFIAUoBDAFA/wD/AP8ADwD/dAV0"

  def main(args: Array[String]): Unit = {

    var finished = false;

    //  ProgramState.config.strategy.setValue("cgro") // STRATEGY! names: cgro taro30 taro50 mgro30

    val (sid, spriteMapF, floorMapF) = ScenarioCache.localInstance.loadScenario(DefaultFloors.dfSportsHall40)

    spriteMapF.onComplete(sm => floorMapF.onComplete(fm => {
      val spriteMap = sm.get
      val floorMap = fm.get

      val startTime = System.nanoTime()
      printExecution(spriteMap, floorMap)
      //testNewPathfinding(el, floorMap)
      val endTime = System.nanoTime()
      val timeDiff = s"${(endTime - startTime) / 1000000000.0}s"
      println("--- finished in " + timeDiff)
      finished = true
    }))

    var waited = 0
    while (!finished) {
      Thread.sleep(1000)
      waited = waited + 1
    }

    println("---> really finished after " + waited + "s!")
  }

  def getEvacuation(spriteMap: EvaSpriteMap, floorMap: EvaFloorMap): Evacuation = {
    val timeStart: Long = System.nanoTime()
    val eva = EvacuationStep.calculateEvacuation(floorMap, ProgramState.config.neighbourhood.getValue.value, ProgramState.config.strategy.getValue.value)
    val timeEnd: Long = System.nanoTime()

    //  println("diff: " + (timeEnd - timeStart) / 1000000 / 1000.0 + "s, using strategy: " + eva.strategyName)
    eva
  }


  def drawExecution(spriteMap: EvaSpriteMap, floorMap: EvaFloorMap): Unit = {
    System.out.println("-- started at: " + new Date())
    val eva = getEvacuation(spriteMap, floorMap)

    val tileDir = new File("S:\\Nextcloud\\Andre\\Arbeit\\Dr\\Projects\\Evakuierung\\Git Programmier Projekt\\EvaProject\\homepage\\img\\tiles\\default\\32").toPath
    val outPath: Path = new File("C:\\Users\\musterhafter\\Pictures\\Eva").toPath.resolve(System.nanoTime().toString)

    println("writing to: " + outPath.toString)

    val drawer = EvaMapDrawer(tileDir, 32, Color.white)


    val steps = List(0) ++ eva.steps
    println("created drawer, drawing steps: " + steps)


    steps.zipWithIndex.foreach(tup => {
      println("drawing: " + tup)
      val stepMicroStepNr = tup._1
      val state = eva.states(stepMicroStepNr)
      val floorMap = FloorMatrix(state.floorMatrix)
      val dest = outPath.resolve("steps").resolve(s"${tup._2}-$stepMicroStepNr.png")

      drawer.drawState(state, dest)
    })

    println("finished steps, drawing states!")
    val printEvery = (eva.states.size / 100)
    eva.states.zipWithIndex.foreach(tup => {

      if (tup._2 % printEvery == 0) {
        val percent = tup._2 * 100.0 / eva.states.size
        println("Drawing state " + tup._2 + "/" + eva.states.size + " (=" + percent + "%)")
      }
      val floorMap = FloorMatrix(tup._1.floorMatrix)
      val dest = outPath.resolve("states").resolve(s"${tup._2}.png")

      drawer.drawState(tup._1, dest)
    }
    )


  }

  def testNewPathfinding(spriteMap: EvaSpriteMap, floorMap: EvaFloorMap): Unit = {

    val graph = floorMap.floorMatrix.asGraph(Neighbourhood.neumann)
    val calc = new RoutingOptionsToDestinationCalculator()

    val res = calc.routingOptionsMap(graph, MatrixPosition(40, 7).in(floorMap.floorMatrix.dim))
    /*
        println("\n\n\n---\n\n\n")
        res.keys().foreach(key => {
          println(key.cPos + " -> " + " (4,4) " + ": ")
          res(key).foreach(value => {
            println("    " + value.curPos + " -> " + value.destination + " (over " + value.nextStep + " in " + value.remainingDistance + ")")
          })
        })
    */
  }

  def printCompression(spriteMap: EvaSpriteMap, floorMap: EvaFloorMap): Unit = {
    FloorMapIO(spriteMap).encode(floorMap)
  }


  def printExecution(spriteMap: EvaSpriteMap, floorMap: EvaFloorMap): Unit = {
    System.out.println("-- started at: " + new Date())
    val eva = getEvacuation(spriteMap, floorMap)
    /*
         eva.states.zipWithIndex.foreach(tup => {
           println("Step " + eva.stepNr(tup._2) + ", State: " + tup._2 + ":\n" + FloorMapIO(spriteMap).encode(tup._1) + "\n")
         })
    */

  }
}
