package workbook.workbookHtmlElements.visualization

import contentmanagement.model.color.RGBColor

final case class VisualizationConfig(
    marginX: Double = 32,
    marginY: Double = 40,
    horizontalLayerSpacing: Double = 140,
    verticalNodeSpacing: Double = 36,
    sectionPaddingX: Double = 20,
    sectionPaddingY: Double = 16,
    sectionMinWidth: Double = 180,
    titleHeight: Double = 20,
    titleSpacing: Double = 8,
    bubbleHeight: Double = 28,
    bubbleSpacing: Double = 12,
    bubbleMinWidth: Double = 56,
    bubbleMaxWidth: Double = 200,
    sectionCornerRadius: Double = 18,
    sectionBorderWidth: Double = 2,
    exerciseCornerRadius: Double = 14,
    exerciseBorderWidth: Double = 1.5,
    exerciseLabelPadding: Double = 8,
    exerciseFontSize: Int = 11,
    backgroundColor: RGBColor = RGBColor(255, 255, 255),
    requiredColor: RGBColor = RGBColor(0, 88, 124),
    recommendedColor: RGBColor = RGBColor(60, 133, 163),
    sectionFillColor: RGBColor = RGBColor(224, 236, 242),
    sectionBorderColor: RGBColor = RGBColor(38, 72, 94),
    bubbleFillColor: RGBColor = RGBColor(0, 88, 124),
    bubbleBorderColor: RGBColor = RGBColor(0, 88, 124),
    titleColor: RGBColor = RGBColor(21, 41, 54),
    labelColor: RGBColor = RGBColor(70, 70, 70),
    titleFontSize: Int = 13,
    arrowHeadLength: Double = 12,
    arrowHeadWidth: Double = 8,
    edgeStrokeWidth: Double = 2,
    edgeVerticalSpacing: Double = 18,
    arrowEndOffset: Double = 12,
    arrowStartOffset: Double = 12,
    edgeCurveStrength: Double = 0.55,
    edgeCurveVerticalBendFactor: Double = 0.6,
    recommendedDashPattern: Seq[Double] = Seq(12.0, 6.0)
)
